function viplab(){var eb='',bb=' top: -1000px;',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',kb='");',Cb='#',Ob='&',uc='.cache.js',Eb='/',Kb='//',dc='16CE4BE011F5634518ABAD69D717F2FD',ec='1A7928CF803740A933FE38AD236D69FC',fc='3CB0022AB64391E855299B2D289B9E7C',gc='4722E16953BEBD57E93342BAF4023F54',hc='4EDFE256AA6FB3A4D1ADAADBD8C6BC87',jc='5BCCA681BC7981488B8FF2B24796C4F0',kc='6831B3EAB6BE5EE1837C5606353EF73E',lc='7FEB22CE3B8ECC1F24CA847BE41A336A',mc='823F42DB4132EED5CA47237E9AF05CBA',nc='9A070DBD47DC72A74A97089B6B7EF236',oc='9C6FABDA1AA99F93A0C88F37253BDDC5',tc=':',tb='::',Hc=':moduleBase',db='<!doctype html>',fb='<html><head><\/head><body><\/body><\/html>',wb='=',Db='?',pc='B918EC1C697A4CFA849F8A3DE4EE98C2',yb='Bad handler "',qc='C4A1A429F12A54FE64324E2BB3762322',cb='CSS1Compat',ib='Chrome',hb='DOMContentLoaded',Y='DUMMY',rc='E04006C3D4960008F4FAC1FBA8A27B07',sc='E51CC6362852701B5C725FF391BEDCB9',Gc='Ignoring non-whitelisted Dev Mode URL: ',Rb='Unexpected exception in locale detection, using default: ',Qb='_',Fc='__gwtDevModeHook:viplab',Pb='__gwt_Locale',Ec='_gwt_dummy_',Jb='base',Hb='baseUrl',T='begin',Z='body',S='bootstrap',Gb='clear.cache.gif',vb='content',cc='de',Mb='default',ic='en',Bc='end',jb='eval("',Dc='file:',Zb='gecko',$b='gecko1_8',U='gwt.codesvr.viplab=',V='gwt.codesvr=',Ac='gwt/clean/clean.css',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',pb='head',yc='href',Cc='http:',Wb='ie10',Yb='ie8',Xb='ie9',$='iframe',Fb='img',mb='javascript',_='javascript:""',vc='link',zc='loadExternalRefs',Lb='locale',Nb='locale=',qb='meta',ob='moduleRequested',nb='moduleStartup',Vb='msie',rb='name',ab='position:absolute; width:0; height:0; border:none; left: -1000px;',wc='rel',Ub='safari',lb='script',ac='selectingPermutation',X='startup',xc='stylesheet',gb='undefined',_b='unknown',Sb='user.agent',W='viplab',bc='viplab.devmode.js',Ib='viplab.nocache.js',sb='viplab::',Tb='webkit';var q=window;var r=document;t(S,T);function s(){var a=q.location.search;return a.indexOf(U)!=-1||a.indexOf(V)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:W,sessionId:q.__gwtStatsSessionId,subSystem:X,evtGroup:a,millis:(new Date).getTime(),type:b})}}
viplab.__sendStats=t;viplab.__moduleName=W;viplab.__errFn=null;viplab.__moduleBase=Y;viplab.__softPermutationId=0;viplab.__computePropValue=null;viplab.__getPropMap=null;viplab.__gwtInstallCode=function(){};viplab.__gwtStartLoadingFragment=function(){return null};var u=function(){return false};var v=function(){return null};__propertyErrorFunction=null;var w=q.__gwt_activeModules=q.__gwt_activeModules||{};w[W]={moduleName:W};var A;function B(){D();return A}
function C(){D();return A.getElementsByTagName(Z)[0]}
function D(){if(A){return}var a=r.createElement($);a.src=_;a.id=W;a.style.cssText=ab+bb;a.tabIndex=-1;r.body.appendChild(a);A=a.contentDocument;if(!A){A=a.contentWindow.document}A.open();var b=document.compatMode==cb?db:eb;A.write(b+fb);A.close()}
function F(k){function l(a){function b(){if(typeof r.readyState==gb){return typeof r.body!=gb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(hb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(hb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=C();var f=B();var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(jb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(kb));g=f.createElement(lb);g.language=mb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(lb);g.language=mb;g.text=c[i];e.appendChild(g);d(e,g)}}}
viplab.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;r.getElementsByTagName(pb)[0].appendChild(n)}
viplab.__startLoadingFragment=function(a){return I(a)};viplab.__installRunAsyncCode=function(a){var b=C();var c=B().createElement(lb);c.language=mb;c.text=a;b.appendChild(c);b.removeChild(c)};function G(){var c={};var d;var e;var f=r.getElementsByTagName(qb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(rb),k;if(j){j=j.replace(sb,eb);if(j.indexOf(tb)>=0){continue}if(j==ub){k=i.getAttribute(vb);if(k){var l,m=k.indexOf(wb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=eb}c[j]=l}}else if(j==xb){k=i.getAttribute(vb);if(k){try{d=eval(k)}catch(a){alert(yb+k+zb)}}}else if(j==Ab){k=i.getAttribute(vb);if(k){try{e=eval(k)}catch(a){alert(yb+k+Bb)}}}}}v=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;viplab.__errFn=e}
function H(){function e(a){var b=a.lastIndexOf(Cb);if(b==-1){b=a.length}var c=a.indexOf(Db);if(c==-1){c=a.length}var d=a.lastIndexOf(Eb,Math.min(c,b));return d>=0?a.substring(0,d+1):eb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Fb);b.src=a+Gb;a=e(b.src)}return a}
function g(){var a=v(Hb);if(a!=null){return a}return eb}
function h(){var a=r.getElementsByTagName(lb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Ib)!=-1){return e(a[b].src)}}return eb}
function i(){var a=r.getElementsByTagName(Jb);if(a.length>0){return a[a.length-1].href}return eb}
function j(){var a=r.location;return a.href==a.protocol+Kb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==eb){k=h()}if(k==eb){k=i()}if(k==eb&&j()){k=e(r.location.href)}k=f(k);return k}
function I(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return viplab.__moduleBase+a}
function J(){var i=[];var j=0;function k(a,b){var c=i;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
m[Lb]=function(){var b=null;var c=Mb;try{if(!b){var d=location.search;var e=d.indexOf(Nb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Ob,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=v(Lb)}if(!b){b=q[Pb]}if(b){c=b}while(b&&!u(Lb,b)){var h=b.lastIndexOf(Qb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Rb+a)}q[Pb]=c;return b||Mb};l[Lb]={de:0,'default':1,en:2};m[Sb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Tb)!=-1}())return Ub;if(function(){return b.indexOf(Vb)!=-1&&r.documentMode>=10}())return Wb;if(function(){return b.indexOf(Vb)!=-1&&r.documentMode>=9}())return Xb;if(function(){return b.indexOf(Vb)!=-1&&r.documentMode>=8}())return Yb;if(function(){return b.indexOf(Zb)!=-1}())return $b;return _b};l[Sb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};u=function(a,b){return b in l[a]};viplab.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};viplab.__computePropValue=n;q.__gwt_activeModules[W].bindings=viplab.__getPropMap;t(S,ac);if(s()){return I(bc)}var o;try{k([cc,$b],dc);k([Mb,Yb],ec);k([cc,Wb],fc);k([cc,Ub],gc);k([Mb,Ub],hc);k([ic,$b],jc);k([cc,Xb],kc);k([ic,Wb],lc);k([ic,Ub],mc);k([Mb,Xb],nc);k([ic,Xb],oc);k([Mb,Wb],pc);k([cc,Yb],qc);k([ic,Yb],rc);k([Mb,$b],sc);o=i[n(Lb)][n(Sb)];var p=o.indexOf(tc);if(p!=-1){j=parseInt(o.substring(p+1),10);o=o.substring(0,p)}}catch(a){}viplab.__softPermutationId=j;return I(o+uc)}
function K(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(vc);b.setAttribute(wc,xc);b.setAttribute(yc,I(a));r.getElementsByTagName(pb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(zc,T);c(Ac);t(zc,Bc)}
G();viplab.__moduleBase=H();w[W].moduleBase=viplab.__moduleBase;var L=J();if(q){var M=!!(q.location.protocol==Cc||q.location.protocol==Dc);q.__gwt_activeModules[W].canRedirect=M;function N(){var b=Ec;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(M&&N()){var O=Fc;var P=q.sessionStorage[O];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(P)){if(P&&(window.console&&console.log)){console.log(Gc+P)}P=eb}if(P&&!q[O]){q[O]=true;q[O+Hc]=H();var Q=r.createElement(lb);Q.src=P;var R=r.getElementsByTagName(pb)[0];R.insertBefore(Q,R.firstElementChild||R.children[0]);return false}}}K();t(S,Bc);F(L);return true}
viplab.succeeded=viplab();